import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout = ({ children }: { children: ReactNode }) => (
  <>
    <html lang="en">
      <head>
        {/* Aqui você pode adicionar os meta tags, links para estilos, etc. */}
        {/* Exemplo: <meta charSet="UTF-8" /> */}
      </head>
      <body>
        <nav>
          <Navbar />
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  </>
);

export default Layout;
